<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.xprevel.util.api</groupId>
        <artifactId>api-compatibility-kit</artifactId>
        <version>2.0.0</version>
    </parent>

    <artifactId>api-compatibility-kit-spring-webmvc-starter</artifactId>
    <packaging>jar</packaging>

    <name>api-compatibility-kit-spring-webmvc-starter</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.xprevel.util.api</groupId>
            <artifactId>api-compatibility-kit-spring-webmvc</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
